### ISSUE TITLE
Warning: Declaration of ApiController::config() should be compatible with ControllerBase::config

### ISSUE THREAD

**Issue by markst** [markst/pbs-schedule-module#6]
`Warning: Declaration of Drupal\api_proxy_pbs\Controller\ApiController::config() should be compatible with Drupal\Core\Controller\ControllerBase::config($name) in include() (line 18 of /var/www/pbss_master_build_20/web/modules/custom/api_proxy_pbs/src/Controller/ApiController.php)`

**Comment by markst** [comment]
Not sure I understand this one, is it due to `ApiController` naming of `protected function config()`?
Perhaps we just need to rename it `protected function settings()`? @lucashodge

**Comment by lucashodge** [comment]
Hi Mark,

When you getting this error? What url are you requesting, I can try debugging on my local machine?

Cheers,
Lucas

**Comment by markst** [comment]
@lucashodge in the recent repots `/admin/reports/dblog`. Might not be anything to worry about.

**Comment by lucashodge** [comment]
I will explore in more detail later and see what I can find.

**Comment by lucashodge** [comment]
@markst the function needs an argument. it should be:

protected function configuration($name)

**Comment by markst** [comment]
ah true! I forgot I already had an issue relating to this. 

https://github.com/markst/pbs-schedule-module/issues/8

@lucashodge  hopefully it's resolved by: https://github.com/markst/pbs-schedule-module/pull/9

**Comment by markst** [comment]
Resolved by https://github.com/markst/pbs-schedule-module/pull/9
